"""initial durable schema

Revision ID: 6f6be8e4090d
Revises: 
Create Date: 2026-07-27 22:09:13.089767
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6f6be8e4090d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections'))
    )
    op.create_table('recognition_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recognition_cache'))
    )
    op.create_index(op.f('ix_recognition_cache_cache_key'), 'recognition_cache', ['cache_key'], unique=True)
    op.create_table('recognition_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.String(length=60), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('supported_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recognition_providers'))
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('beverage_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('producer', sa.String(length=180), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photo_path', sa.Text(), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('alcohol_percent', sa.Float(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('external_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('personal_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_beverage_references_collection_id_collections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_beverage_references'))
    )
    op.create_index(op.f('ix_beverage_references_barcode'), 'beverage_references', ['barcode'], unique=False)
    op.create_index(op.f('ix_beverage_references_category'), 'beverage_references', ['category'], unique=False)
    op.create_index(op.f('ix_beverage_references_collection_id'), 'beverage_references', ['collection_id'], unique=False)
    op.create_index('ix_reference_search', 'beverage_references', ['collection_id', 'name', 'producer'], unique=False)
    op.create_table('collection_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_collection_members_collection_id_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_collection_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_members')),
    sa.UniqueConstraint('collection_id', 'user_id', name=op.f('uq_collection_members_collection_id'))
    )
    op.create_index(op.f('ix_collection_members_collection_id'), 'collection_members', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_members_user_id'), 'collection_members', ['user_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('qr_code', sa.String(length=200), nullable=True),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id IS DISTINCT FROM parent_id', name=op.f('ck_locations_location_not_self_parent')),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_locations_collection_id_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], name=op.f('fk_locations_parent_id_locations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    sa.UniqueConstraint('collection_id', 'parent_id', 'name', name=op.f('uq_locations_collection_id')),
    sa.UniqueConstraint('qr_code', name=op.f('uq_locations_qr_code'))
    )
    op.create_index(op.f('ix_locations_collection_id'), 'locations', ['collection_id'], unique=False)
    op.create_index(op.f('ix_locations_parent_id'), 'locations', ['parent_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_table('variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('vintage', sa.String(length=30), nullable=False),
    sa.Column('volume_ml', sa.Integer(), nullable=True),
    sa.Column('batch', sa.String(length=100), nullable=False),
    sa.Column('format', sa.String(length=60), nullable=False),
    sa.Column('edition', sa.String(length=100), nullable=False),
    sa.Column('alcohol_percent', sa.Float(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['beverage_references.id'], name=op.f('fk_variants_reference_id_beverage_references'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variants')),
    sa.UniqueConstraint('reference_id', 'vintage', 'volume_ml', 'batch', 'format', 'edition', name=op.f('uq_variants_reference_id')),
    sa.UniqueConstraint('sku', name=op.f('uq_variants_sku'))
    )
    op.create_index(op.f('ix_variants_reference_id'), 'variants', ['reference_id'], unique=False)
    op.create_table('open_containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remaining_level', sa.String(length=30), nullable=False),
    sa.Column('consume_by', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_open_containers_location_id_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name=op.f('fk_open_containers_variant_id_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_open_containers'))
    )
    op.create_index(op.f('ix_open_containers_status'), 'open_containers', ['status'], unique=False)
    op.create_index(op.f('ix_open_containers_variant_id'), 'open_containers', ['variant_id'], unique=False)
    op.create_table('purchase_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seller', sa.String(length=180), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('packaging', sa.String(length=50), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=True),
    sa.Column('total_price_cents', sa.Integer(), nullable=True),
    sa.Column('document_path', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name=op.f('fk_purchase_lots_variant_id_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_lots'))
    )
    op.create_index(op.f('ix_purchase_lots_variant_id'), 'purchase_lots', ['variant_id'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('planned_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('occasion', sa.String(length=180), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_reservations_quantity_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reservations_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name=op.f('fk_reservations_variant_id_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservations'))
    )
    op.create_index(op.f('ix_reservations_status'), 'reservations', ['status'], unique=False)
    op.create_index(op.f('ix_reservations_user_id'), 'reservations', ['user_id'], unique=False)
    op.create_index(op.f('ix_reservations_variant_id'), 'reservations', ['variant_id'], unique=False)
    op.create_table('stock_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('source_location_id', sa.Integer(), nullable=True),
    sa.Column('target_location_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('state_before', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state_after', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('terminal', sa.String(length=120), nullable=False),
    sa.Column('sync_status', sa.String(length=30), nullable=False),
    sa.Column('undone_by', sa.Integer(), nullable=True),
    sa.Column('undo_of', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_location_id'], ['locations.id'], name=op.f('fk_stock_events_source_location_id_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_location_id'], ['locations.id'], name=op.f('fk_stock_events_target_location_id_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['undo_of'], ['stock_events.id'], name=op.f('fk_stock_events_undo_of_stock_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['undone_by'], ['stock_events.id'], name=op.f('fk_stock_events_undone_by_stock_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_stock_events_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name=op.f('fk_stock_events_variant_id_variants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_events'))
    )
    op.create_index(op.f('ix_stock_events_created_at'), 'stock_events', ['created_at'], unique=False)
    op.create_index('ix_stock_events_created_desc', 'stock_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_events_event_type'), 'stock_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_stock_events_operation_id'), 'stock_events', ['operation_id'], unique=True)
    op.create_index(op.f('ix_stock_events_variant_id'), 'stock_events', ['variant_id'], unique=False)
    op.create_table('stock_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('packaging', sa.String(length=50), nullable=False),
    sa.Column('units_per_package', sa.Integer(), nullable=False),
    sa.Column('closed_packages', sa.Integer(), nullable=False),
    sa.Column('package_state', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('closed_packages >= 0', name=op.f('ck_stock_positions_closed_packages_nonnegative')),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_stock_positions_quantity_nonnegative')),
    sa.CheckConstraint('reserved_quantity <= quantity', name=op.f('ck_stock_positions_reserved_lte_quantity')),
    sa.CheckConstraint('reserved_quantity >= 0', name=op.f('ck_stock_positions_reserved_nonnegative')),
    sa.CheckConstraint('units_per_package > 0', name=op.f('ck_stock_positions_units_per_package_positive')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_stock_positions_location_id_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name=op.f('fk_stock_positions_variant_id_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_positions')),
    sa.UniqueConstraint('location_id', name=op.f('uq_stock_positions_location_id'))
    )
    op.create_index(op.f('ix_stock_positions_location_id'), 'stock_positions', ['location_id'], unique=False)
    op.create_index(op.f('ix_stock_positions_variant_id'), 'stock_positions', ['variant_id'], unique=False)
    op.create_table('tastings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('meal', sa.String(length=300), nullable=False),
    sa.Column('occasion', sa.String(length=300), nullable=False),
    sa.Column('people', sa.String(length=300), nullable=False),
    sa.Column('photo_path', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tastings_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name=op.f('fk_tastings_variant_id_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tastings'))
    )
    op.create_index(op.f('ix_tastings_user_id'), 'tastings', ['user_id'], unique=False)
    op.create_index(op.f('ix_tastings_variant_id'), 'tastings', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tastings_variant_id'), table_name='tastings')
    op.drop_index(op.f('ix_tastings_user_id'), table_name='tastings')
    op.drop_table('tastings')
    op.drop_index(op.f('ix_stock_positions_variant_id'), table_name='stock_positions')
    op.drop_index(op.f('ix_stock_positions_location_id'), table_name='stock_positions')
    op.drop_table('stock_positions')
    op.drop_index(op.f('ix_stock_events_variant_id'), table_name='stock_events')
    op.drop_index(op.f('ix_stock_events_operation_id'), table_name='stock_events')
    op.drop_index(op.f('ix_stock_events_event_type'), table_name='stock_events')
    op.drop_index('ix_stock_events_created_desc', table_name='stock_events')
    op.drop_index(op.f('ix_stock_events_created_at'), table_name='stock_events')
    op.drop_table('stock_events')
    op.drop_index(op.f('ix_reservations_variant_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_user_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_status'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_purchase_lots_variant_id'), table_name='purchase_lots')
    op.drop_table('purchase_lots')
    op.drop_index(op.f('ix_open_containers_variant_id'), table_name='open_containers')
    op.drop_index(op.f('ix_open_containers_status'), table_name='open_containers')
    op.drop_table('open_containers')
    op.drop_index(op.f('ix_variants_reference_id'), table_name='variants')
    op.drop_table('variants')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_locations_parent_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_collection_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_collection_members_user_id'), table_name='collection_members')
    op.drop_index(op.f('ix_collection_members_collection_id'), table_name='collection_members')
    op.drop_table('collection_members')
    op.drop_index('ix_reference_search', table_name='beverage_references')
    op.drop_index(op.f('ix_beverage_references_collection_id'), table_name='beverage_references')
    op.drop_index(op.f('ix_beverage_references_category'), table_name='beverage_references')
    op.drop_index(op.f('ix_beverage_references_barcode'), table_name='beverage_references')
    op.drop_table('beverage_references')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('recognition_providers')
    op.drop_index(op.f('ix_recognition_cache_cache_key'), table_name='recognition_cache')
    op.drop_table('recognition_cache')
    op.drop_table('collections')
    # ### end Alembic commands ###

